### ISSUE TITLE
What The Fr*ck  Is This

### ISSUE THREAD

**Issue by cattyngmd** [gerald0mc/JustAnotherEconomyPlugin#1]
https://github.com/gerald0mc/JustAnotherEconomyPlugin/blob/1dc16b34e70c7a34f2d336ae07377030854b0e1b/src/main/java/me/gerald/economy/command/CommandManager.java#L211

**Comment by 3jq** [comment]
you don't understand gerald's dream is being yandere

**Comment by cattyngmd** [comment]
> you don't understand gerald's dream is to become yanderedev
on god
